modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
logoFile = "expandedae.png"

[[mods]]
modId = "expandedae"
version = "2.0.0-NEO"
displayName = "Expanded AE"
authors = "Kolja"
description = '''Only adds a bigger pattern provider, for now.'''

[[mixins]]
    config = "mixins.expandedae.json"

[[dependencies.expandedae]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedae]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandedae]]
modId = "ae2"
type = "REQUIRED"
ordering = "AFTER"
side = "BOTH"

[[dependencies.expandedae]]
modId = "extendedae"
type = "REQUIRED"
ordering = "AFTER"
side = "BOTH"

[[dependencies.expandedae]]
modId = "megacells"
type = "OPTIONAL"
ordering = "AFTER"
side = "BOTH"

[[dependencies.expandedae]]
modId = "ae2wtlib_api"
type = "REQUIRED"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.expandedae]]
modId = "architectury"
type = "OPTIONAL"
ordering = "AFTER"
side = "BOTH"

[[dependencies.expandedae]]
modId = "curios"
type = "OPTIONAL"
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"